server:
  port: 3000
  host: "localhost"

JWTSecret: "your_jwt_secret_key"

database:
  user: "your_username"
  host: 47.84.63.130
  port: 5432
  password: "your_password"
  name: "angi"

redis:
  host: 8.219.120.11
  port: 6379
  db: 3
  password: "thuc@nh"
