server:
  port: 3000
  host: "localhost"

JWTSecret: "your_jwt_secret_key"

database:
  user: "admin"
  host: "localhost"
  port: 3306
  password: "secret"
  name: "mydb"

redis:
  host: "localhost"
  port: 6379
  db: 3
  password: "your_redis_password"
